export const testData = [
  {
    testName: "COMPLETE BLOOD PICTURE (CBP),EDTA whole Blood",
    fastingStatus: false,
    price: 410,
  },
  {
    testName: "HBA1c (Glycosylated Hemoglobin)",
    fastingStatus: false,
    price: 590,
  },
  {
    testName: "Complete Urine Examination (CUE),Urine",
    fastingStatus: true,
    price: 290,
  },
  {
    testName: "Liver Function Test (LFT),Serum",
    fastingStatus: false,
    price: 760,
  },
  { testName: "Vitamin D Total", fastingStatus: false, price: 1770 },
  { testName: "LIPID PROFILE", fastingStatus: false, price: 690 },
  { testName: "Vitamin B12", fastingStatus: false, price: 1440 },
  { testName: "C-Reactive Protein (CRP)", fastingStatus: false, price: 530 },
  { testName: "Random Plasma glucose", fastingStatus: false, price: 130 },
  { testName: "Calcium", fastingStatus: false, price: 320 },
  {
    testName: "ERYTHROCYTE SEDIMENTATION RATE (ESR)",
    fastingStatus: false,
    price: 240,
  },
  {
    testName: "Culture and Sensitivity (Routine),Urine",
    fastingStatus: true,
    price: 690,
  },
  { testName: "Complete Blood Count (CBC)", fastingStatus: false, price: 390 },
  { testName: "Creatinine", fastingStatus: false, price: 250 },
  { testName: "Cholesterol Total", fastingStatus: false, price: 380 },
  { testName: "Uric Acid", fastingStatus: false, price: 330 },
  { testName: "PROTHROMBIN TIME", fastingStatus: false, price: 460 },
  { testName: "BLOOD GROUPING & Rh TYPING", fastingStatus: false, price: 250 },
  { testName: "VDRL/RPR (Syphilis),Serum", fastingStatus: false, price: 390 },
  { testName: "Folate (Folic Acid)", fastingStatus: false, price: 1330 },
  { testName: "Widal Slide Method, Serum", fastingStatus: false, price: 530 },
  { testName: "Electrolytes,Serum", fastingStatus: false, price: 590 },
  {
    testName: "HIV I & II ANTIBODIES by RAPID, Serum",
    fastingStatus: false,
    price: 590,
  },
  {
    testName: "Hepatitis B Surface Antigen (HBsAg) Rapid,serum",
    fastingStatus: false,
    price: 500,
  },
  { testName: "Phosphorus", fastingStatus: false, price: 320 },
  { testName: "IgE - Total", fastingStatus: false, price: 880 },
  { testName: "Urea", fastingStatus: false, price: 250 },
  {
    testName: "ACTIVATED PARTIAL THROMBOPLASTIN TIME (APTT)",
    fastingStatus: false,
    price: 590,
  },
  { testName: "Prolactin (PRL)", fastingStatus: false, price: 760 },
  { testName: "Ferritin", fastingStatus: false, price: 1100 },
  {
    testName: "ABSOLUTE EOSINOPHIL COUNT (AEC)",
    fastingStatus: false,
    price: 390,
  },
  { testName: "Free T4 (FT4)", fastingStatus: false, price: 760 },
  { testName: "Iron", fastingStatus: false, price: 530 },
  { testName: "Free T3 (FT3)", fastingStatus: false, price: 760 },
  { testName: "Magnesium", fastingStatus: false, price: 640 },
  {
    testName: "FSH (Follicle Stimulating Hormone)",
    fastingStatus: false,
    price: 760,
  },
  {
    testName: "Luteinizing hormone(LH) ,SERUM",
    fastingStatus: false,
    price: 760,
  },
  {
    testName: "HIV 1 & II Antibodies ,Serum",
    fastingStatus: false,
    price: 760,
  },
  {
    testName: "HEPATITIS C VIRUS (HCV) ,Serum",
    fastingStatus: false,
    price: 880,
  },
  {
    testName: "AMH (Anti Mullerian Hormone)",
    fastingStatus: false,
    price: 2870,
  },
  { testName: "Transferrin Saturation", fastingStatus: false, price: 530 },
  {
    testName: "hs-CRP( High SensitiveC-Reactive Protein )",
    fastingStatus: false,
    price: 880,
  },
  { testName: "Blood Urea Nitrogen (BUN)", fastingStatus: false, price: 250 },
  { testName: "Potassium", fastingStatus: false, price: 390 },
  { testName: "Amylase", fastingStatus: false, price: 530 },
  { testName: "Sodium", fastingStatus: false, price: 390 },
  {
    testName: "TSH (Thyroid Stimulating Hormone) - Ultrasensitive",
    fastingStatus: true,
    price: 390,
  },
  {
    testName: "Urine Protein Creatinine Ratio - Spot",
    fastingStatus: true,
    price: 530,
  },
  {
    testName: "Maternal Screen -Dual Marker with Graph (First Trimester),Serum",
    fastingStatus: false,
    price: 3500,
  },
  { testName: "Lipase", fastingStatus: false, price: 640 },
  { testName: "Drug of Abuse 6 drug Panel", fastingStatus: true, price: 2540 },
  {
    testName: "Total Iron Binding Capacity (TIBC)",
    fastingStatus: false,
    price: 880,
  },
  { testName: "BUN/Creatinine Ratio,Serum", fastingStatus: false, price: 390 },
  { testName: "Pro Calcitonin(PCT)", fastingStatus: false, price: 3470 },
  { testName: "Testosterone Total", fastingStatus: false, price: 880 },
  {
    testName: "HEPATITIS B SURFACE ANTIGEN (Hbs Ag) ,Serum",
    fastingStatus: false,
    price: 640,
  },
  {
    testName: "Bilirubin (Total, Direct, Indirect)",
    fastingStatus: false,
    price: 530,
  },
  { testName: "Microalbumin Urine - Spot", fastingStatus: true, price: 640 },
  { testName: "Biopsy Specimen, Small Size", fastingStatus: false, price: 880 },
  {
    testName: "PSA Total (Prostate Specific Antigen)",
    fastingStatus: false,
    price: 880,
  },
  { testName: "Biopsy Specimen,Large", fastingStatus: false, price: 1440 },
  {
    testName: "NT-pro BNP(N-Terminal pro B-Type Natriuretic Peptide)",
    fastingStatus: false,
    price: 2940,
  },
  {
    testName:
      "Anti TPO/A-TPO (Thyroid Peroxidase antibody)/Anti - Microsomal Antibody",
    fastingStatus: true,
    price: 1760,
  },
  { testName: "Homocysteine - serum", fastingStatus: true, price: 1540 },
  { testName: "Progesterone", fastingStatus: false, price: 880 },
  { testName: "RETICULOCYTE COUNT", fastingStatus: false, price: 380 },
  { testName: "STOOL FOR OCCULT BLOOD", fastingStatus: false, price: 240 },
  {
    testName: "D-Dimer,Sodium Citrate Plasma",
    fastingStatus: false,
    price: 1990,
  },
  { testName: "Ammonia, EDTA Plasma", fastingStatus: false, price: 1320 },
  {
    testName: "Culture and Sensitivity (Routine) ,Stool",
    fastingStatus: false,
    price: 690,
  },
  {
    testName: "Culture and Sensitivity (Routine),Vaginal Swab",
    fastingStatus: false,
    price: 690,
  },
  { testName: "Lactate Dehyrogenase (LDH)", fastingStatus: false, price: 640 },
  { testName: "Anti Streptolysin-O (ASO)", fastingStatus: false, price: 610 },
  { testName: "Biopsy Specimen,Medium", fastingStatus: false, price: 1320 },
  {
    testName: "STOOL FOR REDUCING SUBSTANCES",
    fastingStatus: false,
    price: 240,
  },
  {
    testName: "Culture and Sensitivity (Routine)- Pus",
    fastingStatus: false,
    price: 690,
  },
  { testName: "Albumin - Serum", fastingStatus: false, price: 200 },
  { testName: "Insulin (Fasting)", fastingStatus: false, price: 1000 },
  {
    testName: "SGPT/ALT (Alanine Transaminase)",
    fastingStatus: false,
    price: 250,
  },
  {
    testName: "HB Electrophoresis - HPLC,EDTA Whole Blood",
    fastingStatus: false,
    price: 1770,
  },
  { testName: "Apo A1 (Apolipoprotein A1)", fastingStatus: false, price: 1000 },
  { testName: "CPK (Creatine Kinase)", fastingStatus: false, price: 640 },
  { testName: "TB QUANTIFERON", fastingStatus: false, price: 3600 },
  { testName: "DENGUE IgG & IgM (RAPID)", fastingStatus: false, price: 1220 },
  { testName: "COOMBS TEST INDIRECT (ICT)", fastingStatus: false, price: 420 },
  { testName: "Apo B (Apolipoprotein B)", fastingStatus: false, price: 1000 },
  {
    testName: "FLUID FOR CYTOLOGY (ANY BODY FLUID)",
    fastingStatus: false,
    price: 620,
  },
  { testName: "MALARIA PARASITE (SMEAR)", fastingStatus: false, price: 380 },
  {
    testName: "GGT (Gamma Glutamyl Transferase)",
    fastingStatus: false,
    price: 380,
  },
  {
    testName: "CEA (Carcino Embryonic Antigen)",
    fastingStatus: false,
    price: 1320,
  },
  { testName: "ADA -Pleural fluid", fastingStatus: false, price: 530 },
  {
    testName: "Culture and sensitivity (Routine), Wound",
    fastingStatus: false,
    price: 690,
  },
  { testName: "COOMBS TEST DIRECT (DCT)", fastingStatus: false, price: 430 },
  {
    testName:
      "Culture and Sensitivity (Routine),ET Tips/Et Tubes/Central Lines)",
    fastingStatus: false,
    price: 690,
  },
  { testName: "AFB Smear, Any Body Fluids", fastingStatus: true, price: 320 },
  { testName: "C-Peptide", fastingStatus: false, price: 1980 },
  {
    testName: "Anti-Tg/ATg (Anti Thyroglobulin antibody)",
    fastingStatus: false,
    price: 1440,
  },
  {
    testName: "FIBRINOGEN DEGRDATION PRODUCTS (FDP)",
    fastingStatus: false,
    price: 1790,
  },
  {
    testName: "CONVENTIONAL PAP SMEAR FOR CYTOLOGY",
    fastingStatus: false,
    price: 690,
  },
];
